spring:
  datasource:
    url: jdbc:mysql://localhost:3306/students_db
    username: ${env.MYSQL_USER}
    password: ${env.MYSQL_PW}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
jwt:
  secret: ${env.JWT_SECRET}
  expiration: 15 # minutes
client:
  url: http://localhost:4200