spring:
  datasource:
    url: jdbc:mysql://root:09vcyhCz4r0RLoPcKNTu@containers-us-west-203.railway.app:7615/railway
    username: ${env.MYSQL_USER}
    password: ${env.MYSQL_PW}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
jwt:
  secret: ${env.JWT_SECRET}
  expiration: 15 # minutes
  refresh-expiration: 3600
# server:
#    ssl:
#      key-alias: selfsigned
#      key-password: ${env.SSL_SECRET}
#      key-store-password: ${env.SSL_SECRET}
#      key-store: classpath:keystore.jks
#      key-store-provider: SUN
#      key-store-type: JKS
client:
  url: http://localhost:4200
