spring:
  datasource:
    url: jdbc:mysql://localhost:3306/students_db
    username: ${env.MYSQL_USER}
    password: ${env.MYSQL_PW}
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
jwt:
  secret: ${env.JWT_SECRET}